apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  namespace: catalog-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - secretRef:
            name: env-vars
        volumeMounts:
        - name: catalog-data
          mountPath: /data/db
      - name: mongodb
        image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        volumeMounts:
        - name: catalog-data
          mountPath: /data/db
      volumes:
      - name: catalog-data
        persistentVolumeClaim:
          claimName: mongo-data
