apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: catalog-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.volume.storage }}
